### ISSUE TITLE
Using pretrained model

### ISSUE THREAD

**Issue by fh520** [vita-epfl/openpifpaf#161]
First of all, thanks for your great work, it's really expressive.

But i got same issues while training, it can work well without pretrained model, but when using --checkpoint option to load an existing pretrained model, it can't train, and there is not error information given. The torch version is 1.3.0, python version is 3.7, i change the torch version to 1.1.0, but it seems no effects. Sorry to bother you, hope to get some suggestions from you at your free time, thanks!
![image](https://user-images.githubusercontent.com/56997889/67559667-f9f98d00-f74b-11e9-8ec2-b9aa77a8e846.png)
![image](https://user-images.githubusercontent.com/56997889/67559785-32996680-f74c-11e9-8545-74ea854aa03d.png)

**Comment by svenkreiss** [comment]
Actually, it worked ... sort of.

The message you see is just a warning and this particular one can be ignored. I am still trying to figure out how to get rid of it because it is confusing.

Then, it loaded the pretrained model that was trained until epoch 75. In your config, you only ask to train until epoch 75 so it thinks it is done. So ask to train until `--epoch=160` (some new pretrained models are trained until 150) and adjust `--lr-decay` as well. 

I see how this is confusing and will add a warning.
Does this solve it?

**Comment by fh520** [comment]
Thanks for your reply in time, so i modify --epoch from 75 to 76, it can work.

**Comment by svenkreiss** [comment]
Great!
