### ISSUE TITLE
Error in during and after ONNX conversion

### ISSUE THREAD

**Issue by rlrahulkanojia** [vita-epfl/openpifpaf#214]
error in converting resnet18, 50 models to onnx, but shufflenetv2k16w converts fine. 

```
model, _ = openpifpaf.network.factory(checkpoint='resnet18')
apply(model, 'openpifpaf-shulle.onnx')
```
** Error ** AttributeError: 'CompositeField' object has no attribute 'meta'.

On successful conversion of shufflenetv2k16w, on running 
```
polish('shufflenetv2k16w.onnx')
```

Error = IndexError: Input base_net.net.conv1.0.weight is undefined!

please let me know how to solve this

**Comment by svenkreiss** [comment]
Please use only the pretrained models that are currently mentioned in the readme, ie `shufflenetv2k16w` and `shufflenetv2k30w`. Other models are out of date and incompatible with the current version. I hope to have new pretrained resnet models soon, but it might take a few weeks.

If you can use the previous openpifpaf version, try `pip install --upgrade openpifpaf==0.10` and then export the resnet18 model to onnx.

**Comment by rlrahulkanojia** [comment]
Thank You for the quick reply.
As you mentioned  ```shufflenetv2k30w``` should support new changes but the polish function in export_onnx throws an error as mentioned in my question.

**Comment by svenkreiss** [comment]
This could be related: https://github.com/onnx/onnx/issues/2417

Can you try with the `--no-polish` option? That works for me.

If it is due to the above issue, this seems to be a deeper problem on the pytorch/onnx side that might take a while to resolve. In that case, I will change the default behavior such that there will be a `--polish` instead of `--no-polish` so that the default export without flags works.

**Comment by svenkreiss** [comment]
Thanks for reporting this. The issue seems deeper in the pytorch and onnx ecosystem. Right now, I had to also deactivate the checker. In the current version, you can do that with `--no-check`.

At the moment, the only test that is done is that an onnx model is exported and that during the export there were no errors. However, there is no additional check on the exported model. Can you verify that this works now for you?

Thanks.

**Comment by svenkreiss** [comment]
This recent change might be relevant for you (#240) which will be released in 0.11.7.

**Comment by cwlinghk** [comment]
when i do 
```
python3 export_onnx.py --checkpoint shufflenetv2k16 --input-width 641 --input-height 369 --polish --outfile out.onnx
```
I received the following:
```
Traceback (most recent call last):
  File "export_onnx.py", line 156, in <module>
    main()
  File "export_onnx.py", line 150, in main
    polish(args.outfile)
  File "export_onnx.py", line 98, in polish
    polished_model = onnx.utils.polish_model(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/utils.py", line 24, in polish_model
    model = onnx.optimizer.optimize(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: Input 702 is undefined!
```

**Comment by svenkreiss** [comment]
I assume it works without `--polish` @cwlinghk ?

Then the above comments still apply. The issue that I had linked before (https://github.com/onnx/onnx/issues/2417) is still open. It's on their side. Is there anything you think openpifpaf can do here?
