### ISSUE TITLE
Nightowls dataset

### ISSUE THREAD

**Issue by svenkreiss** [vita-epfl/openpifpaf#293]

**Comment by csr** [comment]
Hi Sven & George!

I hope you're all are doing well. @teddykabg and I are touching base on #271 and are looking into implementing the Nightowls plugin (yay!). We created a folder for the plugin and created two files, just like docs suggest. `__init__.py` registers the plugin to make it discoverable:

```
import openpifpaf
from . import datamodule

def register():
    print("Registering Nightowls plugin...")
    openpifpaf.DATAMODULES['nightowls'] = datamodule.Nightowls
```

...and then we create a `DataModule` subclass (`datamodule.py`):

```
import torch
from openpifpaf.datasets import DataModule, Coco
from openpifpaf import metric

try:
    import pycocotools.coco
    # monkey patch for Python 3 compat
    pycocotools.coco.unicode = str
except ImportError:
    pass

class Nightowls(DataModule):
    # Ugh, absolute paths. We'll get rid of them, but for now we're looking to get things started asap
    val_image_dir = '/Users/cesaredecal/nightowlsdata/nightowls_validation/'
    val_annotations = '/Users/cesaredecal/nightowlsdata/validation.json'

    def eval_loader(self):
        eval_data = Coco(
            image_dir=self.val_image_dir,
            ann_file=self.val_annotations,
        )
        return torch.utils.data.DataLoader(eval_data)

    def metrics(self):
        return [metric.Coco(
            pycocotools.coco.COCO(self.val_annotations),
            max_per_image=20,
            category_ids=[1],
            iou_type='keypoints',
        )]
```

We're not too sure about two things and would love to get some help with:

1. Does the `metrics` function look correct? To be honest, I'm not _quite_ sure what we're getting here if it's MR. I'm not sure if we can even do it like that, just straight out of the box.
2. We tried running the prediction module `python3 -m openpifpaf.eval --dataset=nightowls` and we're getting `TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>` ([traceback](https://gist.github.com/csr/03855a53a22b7d3d61bffaf377bec130)). We will look into this more closely, but maybe this error is due to something wrong in the class implementation?

Thank you!

**Comment by csr** [comment]
Just wanted to update here that we ended up using the [Prediction API](https://vita-epfl.github.io/openpifpaf/predict_api.html) which worked very well for us and we were able to get the MR metric.

**Comment by svenkreiss** [comment]
Hello @csr, glad to hear you got it working. I had discussed your questions with @george-adaimi and he can chime in here, too. If you implemented this as individual predictions, it might be slow. The advantage of using the DataLoader from pytorch is that data is pre-fetched from disk and pinned in memory for fast loading to the GPU. So in case you want to pursue the DataModule further, here are some short thoughts:

1. This metric will give you the standard COCO metrics. If you do type bbox, you might want to increase max_per_image to 100 or even 1000 for NightOwls. To get MR, you need to implement that as a new metric.
2. The coco dataset returns additional info that is in dictionaries (meta information about the image) which the default collate function from pytorch cannot deal with. You can get some inspiration here: https://github.com/vita-epfl/openpifpaf/blob/3099359ac8c7c7724c99d59ee325b6632ae04fbf/openpifpaf/datasets/cocodet.py#L192 which creates a data loader that uses OpenPifPaf's collate function.

I'll let @george-adaimi clarify if there are any components of this that he already has and that he can share.
