### ISSUE TITLE
Pose-based tracking?

### ISSUE THREAD

**Issue by nguyenbaviet** [vita-epfl/openpifpaf#302]
Hi, first of all, thanks for the great project.
In this project, you provided a very good method for pose estimation task but i wanna know could it work well for pose tracking task? And how to do that?

**Comment by stubbb** [comment]
There are a few questions here to unpack. 
First, how many poses do you need to track - one or many?
What is the purpose of tracking them - do you want to make sure every identified pose is assigned to correct person from your set or do you want to reduce inference cycles by tracking a few frames in between?
Is this real time?

Either way, my suggestion would be to focus on high inference FPS so that changes between frames are minimal, then compare the keypoints to find out which ones should be the same person.

**Comment by nguyenbaviet** [comment]
@stubbb Thank you for your quick reply
1) At the moment, we use the set of 17 keypoints from COCO format
2) The purpose of this tracking is to keep the unique IDs of people across frames so that we can have an action record of every one.
3) Real-time speed is preferable but not a must

At the moment, we are considering graph convolution network to do the similarity thing. But I'm not so sure about its performance. There is a Staf method which is invented by the authors of OpenPose but it is implemented in C++, which is super time-consuming to understand it.
I'm looking forward to your work in this area in the future. Your PIFPAF is really phenomenal in my opinion

**Comment by svenkreiss** [comment]
Hi @nguyenbaviet , I am glad you like pifpaf. Tracking is indeed a very interesting topic, also for us, but we haven't published anything on it yet. There is section in the dev Guide (currently a bit hard to find) where I have collected related projects: https://vita-epfl.github.io/openpifpaf/dev/intro.html#related-projects
The project on "fall detection" by Wei Loon Cheng includes a simple tracking algorithm and the algorithm is described in the "Person Tracking" section in the blog post. This simple algorithm usually gets you quite far unless your use-case is particularly complicated.
