### ISSUE TITLE
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.

### ISSUE THREAD

**Issue by Ethan0104** [vita-epfl/openpifpaf#385]
I was following the prediction API tutorial on the official website [here,](https://vita-epfl.github.io/openpifpaf/predict_api.html) however when I ran the code on terminal, I got the following message: 
`OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6`
I am running this on a Mac, and I just cannot get the model to predict the image. Any help is appreciated.

**Comment by svenkreiss** [comment]
Interesting. Never seen that. All versions of openpifpaf are tested on Linux, Windows and Mac.

To help debug, can you provide your torch version and your openpifpaf version?
Can you try to run using the command line so that we can be sure there are no other libraries loaded that cause this conflict: https://vita-epfl.github.io/openpifpaf/dev/predict_cli.html

**Comment by Ethan0104** [comment]
thanks for the quick reply. My torch version is 1.8.1 and my openpifpaf version is 0.12.6

**Comment by svenkreiss** [comment]
Great. I am using that same combination on a Mac without problems. So it probably has something to do with other libraries that are loaded simultaneously in your use case. Can you run the predict example on the command line?

**Comment by svenkreiss** [comment]
For example `python3 -m openpifpaf.predict your_image_filename.jpeg`.

**Comment by Ethan0104** [comment]
just tried that, and it seems like I got the same result: 
`INFO:__main__:neural network device: cpu (CUDA available: False, count: 0)
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6`

**Comment by svenkreiss** [comment]
Hmm, are you using conda?

**Comment by svenkreiss** [comment]
This is the test run on Mac for the 0.12.6 release: https://github.com/vita-epfl/openpifpaf/runs/2185613040
You can expand the sections to see how everything is installed. Maybe that gives you a hint to how your system is different.

**Comment by Ethan0104** [comment]
thanks, I'm checking it now

**Comment by Ethan0104** [comment]
I solved it. It was conda, I didn't know it was taking over the default python distribution. What I had to do was to delete the whole conda folder and install libraries on the default distribution. Thanks for your help! 

Just another quick question, is something supposed to happen when I run 
`with openpifpaf.show.image_canvas(im) as ax: annotation_painter.annotations(ax, predictions)`? If I understood this correctly, I should see the image or see it saved, but I don't seem to see any of that. Is there something I'm missing?

**Comment by Ethan0104** [comment]
The visualization issue seemed to be fixed by adding two extra matplotlib lines after: 
![image](https://user-images.githubusercontent.com/35101174/114113534-70268b00-9911-11eb-8086-f683b6a8b9ba.png)

is that the way it is supposed to be done?

**Comment by svenkreiss** [comment]
Regarding conda: that is annoying. I don't use conda myself. I always had trouble with it but many people like it. I will try to see how I can set up unit tests in conda environments so that this doesn't happen in the future or there is at least better documentation.

Regarding the plot: no, you should not have to call `show()` yourself. It should work exactly as in the guide. The guide is created on every commit so if it doesn't work the guide would also not show it. However, I tried to clean the Guide up a bit and there is actually a hidden cell at the top of the page that imports openpifpaf. But it does slightly more:

```
%matplotlib inline
import openpifpaf

openpifpaf.show.Canvas.show = True
openpifpaf.show.Canvas.image_min_dpi = 200
```

So the last two lines configure all plots and the `show = True` line is what you want. It's a bit annoying that this is hidden now and hinders reproducibility. I should fix or document that in a different way.

**Comment by Ethan0104** [comment]
Alright got it, thank you for your work

**Comment by svenkreiss** [comment]
I am putting in this test case with conda on Mac: https://github.com/vita-epfl/openpifpaf/pull/386/checks?check_run_id=2304480570
This passes as is. I didn't have to tweak anything.

There seems to be an issue sometimes when other packages are installed like `mkl` or `intel-openmp`. Maybe those were in your environment. Anyways, you seem to have solved your problem already. All the best for your project.
