### ISSUE TITLE
more skeleton detected

### ISSUE THREAD

**Issue by lianuo** [vita-epfl/openpifpaf#78]
Thank you for your great works.It seems better than the openpose verion.

I run the code and found one problem ,some times there will be two skeleton being detect from single person.What reason do you think to cause this problem?

thanks

**Comment by svenkreiss** [comment]
Maybe try to increase `--instance-threshold`?

The instance score is adjusted during non-max-suppression, which is keypoint based. If not all keypoints are suppressed, the score is still finite.

**Comment by lianuo** [comment]
@svenkreiss Thanks for replay, 
Could you explain how to use the **instance-threshold** and **keypoint-threshold**? 
such as default value and the range of the value.
Thanks

**Comment by innjoshka** [comment]
@lianuo I faced the same problem and I can say that both OpenPose and PifPaf in some cases create multiple skeletons for one person. But I believe because pifpaf uses 2 CNNs (pif and paf) problem with multiple skeletons for each person is clear seen compare to OpenPose.
Right now I'm testing this library to see if it can compare to OpenPose in some cases and give comparable results. And I could remove false-positive additional bboxes setting flag **force_complete_pose=True** as well as increasing threshold for objects **instance_threshold=0.2**

false-positive additional bboxes have low predictive score and their keypoints almost all filled with zero values. I consider that instance score has computed based on % of zero-to-nonzero keypoint values, so we can easely remove them by increasing **instance_threshold**

Hope it will help.

**Comment by lianuo** [comment]
@innjoshka Thanks for you suggestion.
 I drawed the skeleton out ,and find that the two skeleton from single person usually because the model can not distinguish the right and left arm and leg. I think these will not happen in the Alphapose, but in Openpose and PIFPAF, this seems to be a common problem...
